import garage1 from '../assets/images/GarageShelves/GarageShelving1.jpg'
import garage2 from '../assets/images/GarageShelves/GarageShelving2.jpg'
import garage3 from '../assets/images/GarageShelves/GarageShelving3.jpg'
import garage4 from '../assets/images/GarageShelves/GarageShelving4.jpg'
import garage5 from '../assets/images/GarageShelves/GarageShelving5.jpg'
import garage6 from '../assets/images/GarageShelves/GarageShelving6.jpg'
import garage7 from '../assets/images/GarageShelves/GarageShelving7.jpg'
import garage8 from '../assets/images/GarageShelves/GarageShelving8.jpg'
import garage9 from '../assets/images/GarageShelves/GarageShelving9.jpg'
import garage10 from '../assets/images/GarageShelves/GarageShelving10.jpg'
import garage11 from '../assets/images/GarageShelves/GarageShelving11.jpg'
import garage12 from '../assets/images/GarageShelves/GarageShelving12.jpg'
import garage13 from '../assets/images/GarageShelves/GarageShelving13.jpg'
import garage14 from '../assets/images/GarageShelves/GarageShelving14.jpg'
import garage15 from '../assets/images/GarageShelves/GarageShelving15.jpg'
import garage16 from '../assets/images/GarageShelves/GarageShelving16.jpg'
import garage17 from '../assets/images/GarageShelves/GarageShelving17.jpg'
import garage18 from '../assets/images/GarageShelves/GarageShelving18.jpg'
import garage19 from '../assets/images/GarageShelves/GarageShelving19.jpg'
import garage20 from '../assets/images/GarageShelves/GarageShelving20.jpg'
import garage21 from '../assets/images/GarageShelves/GarageShelving21.jpg'
import garage22 from '../assets/images/GarageShelves/GarageShelving22.jpg'
import garage23 from '../assets/images/GarageShelves/GarageShelving23.jpg'
import garage24 from '../assets/images/GarageShelves/GarageShelving24.jpg'
import garage25 from '../assets/images/GarageShelves/GarageShelving25.jpg'
import garage26 from '../assets/images/GarageShelves/GarageShelving26.jpg'
import garage27 from '../assets/images/GarageShelves/GarageShelving27.jpg'
import garage28 from '../assets/images/GarageShelves/GarageShelving28.jpg'
import garage29 from '../assets/images/GarageShelves/GarageShelving29.jpg'
import garage30 from '../assets/images/GarageShelves/GarageShelving30.jpg'
import garage31 from '../assets/images/GarageShelves/GarageShelving31.jpg'
import garage32 from '../assets/images/GarageShelves/GarageShelving32.jpg'
import garage33 from '../assets/images/GarageShelves/GarageShelving33.jpg'
import garage34 from '../assets/images/GarageShelves/GarageShelving34.jpg'

import angle1 from '../assets/images/AngleSupports/AngleShelves1.jpg'
import angle2 from '../assets/images/AngleSupports/AngleShelves2.jpg'
import angle3 from '../assets/images/AngleSupports/AngleShelves3.jpg'
import angle4 from '../assets/images/AngleSupports/AngleShelves4.jpg'
import angle5 from '../assets/images/AngleSupports/AngleShelves5.jpg'
import angle6 from '../assets/images/AngleSupports/AngleShelves6.jpg'
import angle7 from '../assets/images/AngleSupports/AngleShelves7.jpg'
import angle8 from '../assets/images/AngleSupports/AngleShelves8.jpg'
import angle9 from '../assets/images/AngleSupports/AngleShelves9.jpg'
import angle10 from '../assets/images/AngleSupports/AngleShelves10.jpg'
import angle11 from '../assets/images/AngleSupports/AngleShelves11.jpg'
import angle12 from '../assets/images/AngleSupports/AngleShelves12.jpg'
import angle13 from '../assets/images/AngleSupports/AngleShelves13.jpg'
import angle14 from '../assets/images/AngleSupports/AngleShelves14.jpg'
import angle15 from '../assets/images/AngleSupports/AngleShelves15.jpg'
import angle16 from '../assets/images/AngleSupports/AngleShelves16.jpg'
import angle17 from '../assets/images/AngleSupports/AngleShelves17.jpg'
import angle18 from '../assets/images/AngleSupports/AngleShelves18.jpg'
import angle19 from '../assets/images/AngleSupports/AngleShelves19.jpg'
import angle20 from '../assets/images/AngleSupports/AngleShelves20.jpg'
import angle21 from '../assets/images/AngleSupports/AngleShelves21.jpg'
import angle22 from '../assets/images/AngleSupports/AngleShelves22.jpg'
import angle23 from '../assets/images/AngleSupports/AngleShelves23.jpg'
import angle24 from '../assets/images/AngleSupports/AngleShelves24.jpg'
import angle25 from '../assets/images/AngleSupports/AngleShelves25.jpg'
import angle26 from '../assets/images/AngleSupports/AngleShelves26.jpg'
import angle27 from '../assets/images/AngleSupports/AngleShelves27.jpg'
import angle28 from '../assets/images/AngleSupports/AngleShelves28.jpg'
import angle29 from '../assets/images/AngleSupports/AngleShelves29.jpg'
import angle30 from '../assets/images/AngleSupports/AngleShelves30.jpg'
import angle31 from '../assets/images/AngleSupports/AngleShelves31.jpg'
import angle32 from '../assets/images/AngleSupports/AngleShelves32.jpg'
import angle33 from '../assets/images/AngleSupports/AngleShelves33.jpg'
import angle34 from '../assets/images/AngleSupports/AngleShelves34.jpg'
import angle35 from '../assets/images/AngleSupports/AngleShelves35.jpg'
import angle36 from '../assets/images/AngleSupports/AngleShelves36.jpg'
import angle37 from '../assets/images/AngleSupports/AngleShelves37.jpg'
import angle38 from '../assets/images/AngleSupports/AngleShelves38.jpg'
import angle39 from '../assets/images/AngleSupports/AngleShelves39.jpg'
import angle40 from '../assets/images/AngleSupports/AngleShelves40.jpg'

import workbench1 from '../assets/images/Workbenches/Workbench1.jpg'
import workbench2 from '../assets/images/Workbenches/Workbench2.jpg'
import workbench3 from '../assets/images/Workbenches/Workbench3.jpg'
import workbench4 from '../assets/images/Workbenches/Workbench4.jpg'
import workbench5 from '../assets/images/Workbenches/Workbench5.jpg'
import workbench6 from '../assets/images/Workbenches/Workbench6.jpg'
import workbench7 from '../assets/images/Workbenches/Workbench7.jpg'
import workbench8 from '../assets/images/Workbenches/Workbench8.jpg'
import workbench9 from '../assets/images/Workbenches/Workbench9.jpg'
import workbench10 from '../assets/images/Workbenches/Workbench10.jpg'
import workbench11 from '../assets/images/Workbenches/Workbench11.jpg'
import workbench12 from '../assets/images/Workbenches/Workbench12.jpg'
import workbench13 from '../assets/images/Workbenches/Workbench13.jpg'
import workbench14 from '../assets/images/Workbenches/Workbench14.jpg'

import basement1 from '../assets/images/BasementShelves/BasementShelving1.jpg'
import basement2 from '../assets/images/BasementShelves/BasementShelving2.jpg'
import basement3 from '../assets/images/BasementShelves/BasementShelving3.jpg'
import basement4 from '../assets/images/BasementShelves/BasementShelving4.jpg'
import basement5 from '../assets/images/BasementShelves/BasementShelving5.jpg'
import basement6 from '../assets/images/BasementShelves/BasementShelving6.jpg'
import basement7 from '../assets/images/BasementShelves/BasementShelving7.jpg'
import basement8 from '../assets/images/BasementShelves/BasementShelving8.jpg'
import basement9 from '../assets/images/BasementShelves/BasementShelving9.jpg'
import basement10 from '../assets/images/BasementShelves/BasementShelving10.jpg'
import basement11 from '../assets/images/BasementShelves/BasementShelving11.jpg'
import basement12 from '../assets/images/BasementShelves/BasementShelving12.jpg'
import basement13 from '../assets/images/BasementShelves/BasementShelving13.jpg'
import basement14 from '../assets/images/BasementShelves/BasementShelving14.jpg'
import basement15 from '../assets/images/BasementShelves/BasementShelving15.jpg'
import basement16 from '../assets/images/BasementShelves/BasementShelving16.jpg'
import basement17 from '../assets/images/BasementShelves/BasementShelving17.jpg'
import basement18 from '../assets/images/BasementShelves/BasementShelving18.jpg'
import basement19 from '../assets/images/BasementShelves/BasementShelving19.jpg'
import basement20 from '../assets/images/BasementShelves/BasementShelving20.jpg'
import basement21 from '../assets/images/BasementShelves/BasementShelving21.jpg'
import basement22 from '../assets/images/BasementShelves/BasementShelving22.jpg'
import basement23 from '../assets/images/BasementShelves/BasementShelving23.jpg'
import basement24 from '../assets/images/BasementShelves/BasementShelving24.jpg'
import basement25 from '../assets/images/BasementShelves/BasementShelving25.jpg'
import basement26 from '../assets/images/BasementShelves/BasementShelving26.jpg'
import basement27 from '../assets/images/BasementShelves/BasementShelving27.jpg'
import basement28 from '../assets/images/BasementShelves/BasementShelving28.jpg'
import basement29 from '../assets/images/BasementShelves/BasementShelving29.jpg'
import basement30 from '../assets/images/BasementShelves/BasementShelving30.jpg'
import basement31 from '../assets/images/BasementShelves/BasementShelving31.jpg'
import basement32 from '../assets/images/BasementShelves/BasementShelving32.jpg'
import basement33 from '../assets/images/BasementShelves/BasementShelving33.jpg'
import basement34 from '../assets/images/BasementShelves/BasementShelving34.jpg'
import basement35 from '../assets/images/BasementShelves/BasementShelving35.jpg'

import closetPantry1 from '../assets/images/ClosetShelves/ClosetShelves1.jpg'
import closetPantry2 from '../assets/images/ClosetShelves/ClosetShelves2.jpg'
import closetPantry3 from '../assets/images/ClosetShelves/ClosetShelves3.jpg'
import closetPantry4 from '../assets/images/ClosetShelves/ClosetShelves4.jpg'
import closetPantry5 from '../assets/images/ClosetShelves/ClosetShelves5.jpg'
import closetPantry6 from '../assets/images/ClosetShelves/ClosetShelves6.jpg'
import closetPantry7 from '../assets/images/ClosetShelves/ClosetShelves7.jpg'
import closetPantry8 from '../assets/images/ClosetShelves/ClosetShelves8.jpg'
import closetPantry9 from '../assets/images/ClosetShelves/ClosetShelves9.jpg'
import closetPantry10 from '../assets/images/ClosetShelves/ClosetShelves10.jpg'
import closetPantry11 from '../assets/images/ClosetShelves/ClosetShelves11.jpg'
import closetPantry12 from '../assets/images/ClosetShelves/ClosetShelves12.jpg'
import closetPantry13 from '../assets/images/ClosetShelves/ClosetShelves13.jpg'
import closetPantry14 from '../assets/images/ClosetShelves/ClosetShelves14.jpg'

import bookshelves1 from '../assets/images/Bookshelves/Bookshelves1.jpg'
import bookshelves2 from '../assets/images/Bookshelves/Bookshelves2.jpg'
import bookshelves3 from '../assets/images/Bookshelves/Bookshelves3.jpg'
import bookshelves4 from '../assets/images/Bookshelves/Bookshelves4.jpg'
import bookshelves5 from '../assets/images/Bookshelves/Bookshelves5.jpg'
import bookshelves6 from '../assets/images/Bookshelves/Bookshelves6.jpg'
import bookshelves7 from '../assets/images/Bookshelves/Bookshelves7.jpg'

import lockersMudroom1 from '../assets/images/LockersMudrooms/Lockers1.jpg'
import lockersMudroom2 from '../assets/images/LockersMudrooms/Lockers2.jpg'
import lockersMudroom3 from '../assets/images/LockersMudrooms/Lockers3.jpg'
import lockersMudroom4 from '../assets/images/LockersMudrooms/Lockers4.jpg'
import lockersMudroom5 from '../assets/images/LockersMudrooms/Lockers5.jpg'
import lockersMudroom6 from '../assets/images/LockersMudrooms/Lockers6.jpg'
import lockersMudroom7 from '../assets/images/LockersMudrooms/Lockers7.jpg'
import lockersMudroom8 from '../assets/images/LockersMudrooms/Lockers8.jpg'
import lockersMudroom9 from '../assets/images/LockersMudrooms/Lockers9.jpg'
import lockersMudroom10 from '../assets/images/LockersMudrooms/Lockers10.jpg'
import lockersMudroom11 from '../assets/images/LockersMudrooms/Lockers11.jpg'
import lockersMudroom12 from '../assets/images/LockersMudrooms/Lockers12.jpg'
import lockersMudroom13 from '../assets/images/LockersMudrooms/Lockers13.jpg'
import lockersMudroom14 from '../assets/images/LockersMudrooms/Lockers14.jpg'
import lockersMudroom15 from '../assets/images/LockersMudrooms/Lockers15.jpg'
import lockersMudroom16 from '../assets/images/LockersMudrooms/Lockers16.jpg'
import lockersMudroom17 from '../assets/images/LockersMudrooms/MudroomShelves1.jpg'
import lockersMudroom18 from '../assets/images/LockersMudrooms/MudroomShelves2.jpg'

import other1 from '../assets/images/OtherProjects/Trailer.jpg'
import other2 from '../assets/images/OtherProjects/dresser.jpg'
import other3 from '../assets/images/OtherProjects/laundryroom.png'

export const garageShelves = [garage1, garage2, garage3, garage4, garage5, garage6, garage7, garage8, garage9, 
    garage10, garage11, garage12, garage13, garage14, garage15, garage16, garage17, garage18, garage19, 
    garage20, garage21, garage22, garage23, garage24, garage25, garage26, garage27, garage28, garage29, 
    garage30, garage31, garage32, garage33, garage34];
        
export const angleShelves = [angle1, angle2, angle3, angle4, angle5, angle6, angle7, angle8, angle9, 
    angle10, angle11, angle12, angle13, angle14, angle15, angle16, angle17, angle18, angle19, 
    angle20, angle21, angle22, angle23, angle24, angle25, angle26, angle27, angle28, angle29, 
    angle30, angle31, angle32, angle33, angle34, angle35, angle36, angle37, angle38, angle39, angle40];

export const workbenches = [workbench1, workbench2, workbench3, workbench4, workbench5, workbench6, workbench7, 
    workbench8, workbench9, workbench10, workbench11, workbench12, workbench13, workbench14];

export const basementShelves = [basement1, basement2, basement3, basement4, basement5, basement6, basement7, basement8, basement9, 
    basement10, basement11, basement12, basement13, basement14, basement15, basement16, basement17, basement18, basement19, 
    basement20, basement21, basement22, basement23, basement24, basement25, basement26, basement27, basement28, basement29, 
    basement30, basement31, basement32, basement33, basement34, basement35]

export const closetsPantries = [closetPantry1, closetPantry2, closetPantry3, closetPantry4, closetPantry5, closetPantry6, closetPantry7, 
    closetPantry8, closetPantry9, closetPantry10, closetPantry11, closetPantry12, closetPantry13, closetPantry14];

export const bookShelves = [bookshelves1, bookshelves2, bookshelves3, bookshelves4, bookshelves5, 
    bookshelves6, bookshelves7];

export const lockersMudroomShelves = [lockersMudroom1, lockersMudroom2, lockersMudroom3, lockersMudroom4, lockersMudroom5, lockersMudroom6, 
    lockersMudroom7, lockersMudroom8, lockersMudroom9, lockersMudroom10, lockersMudroom11, lockersMudroom12, lockersMudroom13, 
    lockersMudroom14, lockersMudroom15, lockersMudroom16, lockersMudroom17, lockersMudroom18];

export const otherProjects = [other1, other2, other3];